apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: noyusu/spark-standalone-3.5.1:v0.0.17
        command: ["/bin/bash"]
        args: [
          "-c",
          "export SPARK_MASTER_HOST=$(hostname -i); ./sbin/start-master.sh & sleep 2; tail -f /opt/spark/logs/spark--org.apache.spark.deploy.master.Master-1-*.out"
        ]
        env:
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        ports:
        - containerPort: 8080  # Default port for Spark master web UI
        - containerPort: 7077  # Additional port
        volumeMounts:
        - name: spark-logs
          mountPath: /opt/spark/logs
      volumes:
      - name: spark-logs
        emptyDir: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                    - zone-1