apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: spark
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      automountServiceAccountToken: false
      containers:
      - name: spark-worker
        image: noyusu/spark-standalone-3.5.1:v0.0.17
        command: ["/bin/bash"]
        args: ["-c", "./sbin/start-worker.sh $SPARK_MASTER_URL & sleep 2; tail -f /opt/spark/logs/spark--org.apache.spark.deploy.worker.Worker-1-*.out"]
        env:
        - name: SPARK_MASTER_URL
          value: "spark://spark-master-service:7077"
        ports:
        - containerPort: 8081  # Default port for Spark master web UI
        volumeMounts:
        - name: spark-logs
          mountPath: /opt/spark/logs
        - name: spark-storage
          mountPath: /mnt/data
        resources: 
          limits:
            nvidia.com/gpu: 1 # slicing by nvidia-plugin
      volumes:
      - name: spark-logs
        emptyDir: {}
      - name: spark-storage
        persistentVolumeClaim:
          claimName: spark-pvc