apiVersion: v1
kind: Service
metadata:
  name: spark-worker-ui-service
  namespace: spark
spec:
  type: NodePort  # Keeps the service as ClusterIP for internal traffic
  ports:
  - name: webui
    port: 8081
    targetPort: 8081
    protocol: TCP
    nodePort: 32187  # Specify a nodePort to expose on all nodes
  selector:
    app: spark-worker