# 1: cp -r $SPARK_HOME ./spark-home
# 2: docker build -t noyusu/spark-standalone-3.5.1:v0.0.n .
#   -> config v0.0.n, noyusu to yourdockerID
# 3: rm -rf spark-home/
# 4: docker push noyusu/spark-standalone-3.5.1:v0.0.n
#   -> config v0.0.n, noyusu to yourdockerID

# Base image
FROM openjdk:11

# Set environment variable based on the build-time argument
ENV SPARK_HOME /opt/spark

# Copy the contents from the local directory to the image's SPARK_HOME directory
COPY spark-home /opt/spark

# Change working directory to $SPARK_HOME
WORKDIR $SPARK_HOME

RUN apt-get update && \
    apt-get install -y python3.9-distutils && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py

RUN python3 -m pip install numpy torch torchvision torchaudio pyarrow pandas tqdm kafka-python